#!/bin/sh

namespace=${0##*aero_expired_}

if [ "$1" = "autoconf" ]; then
    echo yes
    exit 0
fi

if [ "$1" = "config" ]; then
	echo "graph_title Aerospike expired objects on $namespace namespace"
	echo "aeroexpired.label Expired objects"
	echo "aeroexpired.draw AREA"
	echo "aeroexpired.min 0"
	echo "graph_category Aerospike"
	exit 0
fi 
echo -n "aeroexpired.value " && aql -c "stat namespace ${namespace}" | grep expired_objects | head -n 1 | awk '{print$4}' | tr -d '"'
