#!/bin/sh

namespace=${0##*aero_client_write_}

if [ "$1" = "autoconf" ]; then
    echo yes
    exit 0
fi

if [ "$1" = "config" ]; then
	echo "graph_title Aerospike client write per second on $namespace namespace"
	echo "aerowritesuccess.label Read"
	echo "aerowritesuccess.draw AREA"

	exit 0
fi

TOTALBEFORE=$(aql -c "stat namespace ${namespace}" | grep client_write_success | tr '"' ' ' | head -n 1 | awk '{print$4}')
sleep 1s
TOTALAFTER=$(aql -c "stat namespace ${namespace}" | grep client_write_success | tr '"' ' ' | head -n 1 | awk '{print$4}')


PERSEC=$((TOTALAFTER - TOTALBEFORE))

echo -n "aerowritesuccess.value $PERSEC" 
