#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Aerospike client connections
graph_vlabel Number of connections
aeroclient.label Clients
graph_category Aerospike
EOM
        exit 0;;
esac

CLI=$(asinfo -v statistics -l | grep client_connections |  tr '=' ' ' | awk '{print $2}')
echo "aeroclient.value $CLI"
